from PyQt5 import QtCore, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1546, 649)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 5, 0, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 6, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(Form)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout.addWidget(self.listWidget_2, 7, 0, 1, 2)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 2, 8, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "ToDo:"))
        self.pushButton_3.setText(_translate("Form", "新建事项分类"))
        self.label.setText(_translate("Form", "Click Table:"))
        self.pushButton_2.setText(_translate("Form", "新建待办事项"))
        self.pushButton_5.setText(_translate("Form", "一键安排"))
        self.pushButton_4.setText(_translate("Form", "新建日常任务"))
        self.pushButton.setText(_translate("Form", "新建固定事项"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "00:00-01:59"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("Form", "02:00-03:59"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("Form", "04:00-05:59"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("Form", "06:00-07:59"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("Form", "08:00-09:59"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("Form", "10:00-11:59"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("Form", "12:00-13:59"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("Form", "14:00-15:59"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("Form", "16:00-17:59"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("Form", "18:00-19:59"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("Form", "20:00-21:59"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("Form", "22:00-23:59"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "MON"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "TUE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "WED"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "TUR"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "FRI"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "SAT"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "SUN"))
